#!/bin/bash
#PBS -l nodes=n11-59:ppn=16
#PBS -N PYQUANT_MPI

cd $PBS_O_WORKDIR
module load intel/11.1 mpi/openmpi-1.5.3-intel


MOL1=../../SCF/benzene/benzene.xyz
MOL2=../../SCF/benzene_translated/benzene_translated.xyz

ORBS1=../../SCF/benzene/benzene_orbitals.dat
ORBS2=../../SCF/benzene_translated/benzene_translated_orbitals.dat

NEL1=../../SCF/benzene/benzene_nel.dat
NEL2=../../SCF/benzene_translated/benzene_translated_nel.dat

 
mpirun -np 16 python citrus_mpi.py $MOL1 $MOL2 -mo1 $ORBS1 -mo2 $ORBS2 -nel1 $NEL1 -nel2 $NEL2
